cat_id = {'Book': '6018',
          'Business': '6000',
          'Catalogs': '6022',
          'Education': '6017',
          'Entertainment': '6016',
          'Finance': '6015',
          'Food & Drink': '6023',
          'Games': '6014',
          'Health & Fitness': '6013',
          'Lifestyle': '6012',
          'Medical': '6020',
          'Music': '6011',
          'Navigation': '6010',
          'News': '6009',
          'Newsstand': '6021',
          'Photo & Video': '6008',
          'Productivity': '6007',
          'Reference': '6006',
          'Social Networking': '6005',
          'Sports': '6004',
          'Travel': '6003',
          'Utilities': '6002',
          'Weather': '6001'}



device_list = ["iPad23G",
               "iPad2Wifi",
               "iPadFourthGen",
               "iPadFourthGen4G",
               "iPadMini",
               "iPadMini4G",
               "iPadThirdGen",
               "iPadThirdGen4G",
               "iPhone4",
               "iPhone4S",
               "iPhone5",
               "iPhone5c",
               "iPhone5s",
               "iPodTouchFifthGen",
               "iPhone-3GS",
               "iPhone6",
               "iPhone6Plus",
               "iPodTouchFourthGen",
               "iPodTouchSixthGen",
               "iPad3G",
               "iPadWifi",
               "iPodTouchThirdGen",
               "iPodTouchourthGen",
               "iPhone-3G",
               "iPod-touch-with-mic",
               "iPhone",
               "iPod-touch"]
